"""initial schema

Revision ID: 38acef7bbe92
Revises: 
Create Date: 2026-08-02 09:06:45.111015
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '38acef7bbe92'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('stripe_customer_id', sa.String(length=255), nullable=True),
    sa.Column('plan_status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_stripe_customer_id'), 'users', ['stripe_customer_id'], unique=False)
    op.create_table('monitoring_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('hotel_name_raw', sa.String(length=500), nullable=False),
    sa.Column('hotel_id', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=200), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('check_in', sa.Date(), nullable=False),
    sa.Column('check_out', sa.Date(), nullable=False),
    sa.Column('nights', sa.Integer(), nullable=False),
    sa.Column('room_type_raw', sa.String(length=500), nullable=True),
    sa.Column('board_type', sa.String(length=4), nullable=True),
    sa.Column('adults', sa.Integer(), nullable=True),
    sa.Column('children', sa.Integer(), nullable=True),
    sa.Column('original_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('original_ota', sa.String(length=100), nullable=True),
    sa.Column('refundable', sa.Boolean(), nullable=False),
    sa.Column('cancellation_deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancellation_terms_raw', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_check_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('check_count', sa.Integer(), nullable=False),
    sa.Column('current_best_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('current_best_ota', sa.String(length=100), nullable=True),
    sa.Column('current_best_url', sa.Text(), nullable=True),
    sa.Column('lowest_seen_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('drop_alert_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('lowest_alerted_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('deadline_alert_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_monitoring_jobs_hotel_id'), 'monitoring_jobs', ['hotel_id'], unique=False)
    op.create_index(op.f('ix_monitoring_jobs_next_check_at'), 'monitoring_jobs', ['next_check_at'], unique=False)
    op.create_index(op.f('ix_monitoring_jobs_status'), 'monitoring_jobs', ['status'], unique=False)
    op.create_index(op.f('ix_monitoring_jobs_user_id'), 'monitoring_jobs', ['user_id'], unique=False)
    op.create_table('price_checks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('checked_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('best_matching_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('best_ota', sa.String(length=100), nullable=True),
    sa.Column('raw_response_ref', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['monitoring_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_price_checks_job_id'), 'price_checks', ['job_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_price_checks_job_id'), table_name='price_checks')
    op.drop_table('price_checks')
    op.drop_index(op.f('ix_monitoring_jobs_user_id'), table_name='monitoring_jobs')
    op.drop_index(op.f('ix_monitoring_jobs_status'), table_name='monitoring_jobs')
    op.drop_index(op.f('ix_monitoring_jobs_next_check_at'), table_name='monitoring_jobs')
    op.drop_index(op.f('ix_monitoring_jobs_hotel_id'), table_name='monitoring_jobs')
    op.drop_table('monitoring_jobs')
    op.drop_index(op.f('ix_users_stripe_customer_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
