"""add hotel_candidates and pending statuses

Revision ID: cb7ca9a25719
Revises: 38acef7bbe92
Create Date: 2026-08-02 09:42:03.085850
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'cb7ca9a25719'
down_revision: Union[str, None] = '38acef7bbe92'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('monitoring_jobs', sa.Column('hotel_candidates', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('monitoring_jobs', 'hotel_candidates')
    # ### end Alembic commands ###
